//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `p_vote` program ID.
  pub const P_VOTE_ID: Pubkey = pubkey!("2YwymitHUGW6vwk66cZpVoq5oGD31Ziz41UNokMBrKeY");

