//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#platform;
  pub(crate) mod r#position;
  pub(crate) mod r#vote;

  pub use self::r#platform::*;
  pub use self::r#position::*;
  pub use self::r#vote::*;

