/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from './initializePlatform';
export * from './initializeVote';
export * from './intitializePosition';
export * from './redeemWinnings';
export * from './updatePlatform';
export * from './updatePosition';
