/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { P_VOTE_PROGRAM_ADDRESS } from '../programs';

export const INITIALIZE_VOTE_DISCRIMINATOR = 2;

export function getInitializeVoteDiscriminatorBytes() {
  return getU8Encoder().encode(INITIALIZE_VOTE_DISCRIMINATOR);
}

export type InitializeVoteInstruction<
  TProgram extends string = typeof P_VOTE_PROGRAM_ADDRESS,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<TRemainingAccounts>;

export type InitializeVoteInstructionData = { discriminator: number };

export type InitializeVoteInstructionDataArgs = {};

export function getInitializeVoteInstructionDataEncoder(): FixedSizeEncoder<InitializeVoteInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: INITIALIZE_VOTE_DISCRIMINATOR }),
  );
}

export function getInitializeVoteInstructionDataDecoder(): FixedSizeDecoder<InitializeVoteInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getInitializeVoteInstructionDataCodec(): FixedSizeCodec<
  InitializeVoteInstructionDataArgs,
  InitializeVoteInstructionData
> {
  return combineCodec(
    getInitializeVoteInstructionDataEncoder(),
    getInitializeVoteInstructionDataDecoder(),
  );
}

export type InitializeVoteInput = {};

export function getInitializeVoteInstruction<
  TProgramAddress extends Address = typeof P_VOTE_PROGRAM_ADDRESS,
>(config?: {
  programAddress?: TProgramAddress;
}): InitializeVoteInstruction<TProgramAddress> {
  // Program address.
  const programAddress = config?.programAddress ?? P_VOTE_PROGRAM_ADDRESS;

  const instruction = {
    programAddress,
    data: getInitializeVoteInstructionDataEncoder().encode({}),
  } as InitializeVoteInstruction<TProgramAddress>;

  return instruction;
}

export type ParsedInitializeVoteInstruction<
  TProgram extends string = typeof P_VOTE_PROGRAM_ADDRESS,
> = {
  programAddress: Address<TProgram>;
  data: InitializeVoteInstructionData;
};

export function parseInitializeVoteInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeVoteInstruction<TProgram> {
  return {
    programAddress: instruction.programAddress,
    data: getInitializeVoteInstructionDataDecoder().decode(instruction.data),
  };
}
