/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { P_VOTE_PROGRAM_ADDRESS } from '../programs';

export const REDEEM_WINNINGS_DISCRIMINATOR = 5;

export function getRedeemWinningsDiscriminatorBytes() {
  return getU8Encoder().encode(REDEEM_WINNINGS_DISCRIMINATOR);
}

export type RedeemWinningsInstruction<
  TProgram extends string = typeof P_VOTE_PROGRAM_ADDRESS,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<TRemainingAccounts>;

export type RedeemWinningsInstructionData = { discriminator: number };

export type RedeemWinningsInstructionDataArgs = {};

export function getRedeemWinningsInstructionDataEncoder(): FixedSizeEncoder<RedeemWinningsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: REDEEM_WINNINGS_DISCRIMINATOR }),
  );
}

export function getRedeemWinningsInstructionDataDecoder(): FixedSizeDecoder<RedeemWinningsInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getRedeemWinningsInstructionDataCodec(): FixedSizeCodec<
  RedeemWinningsInstructionDataArgs,
  RedeemWinningsInstructionData
> {
  return combineCodec(
    getRedeemWinningsInstructionDataEncoder(),
    getRedeemWinningsInstructionDataDecoder(),
  );
}

export type RedeemWinningsInput = {};

export function getRedeemWinningsInstruction<
  TProgramAddress extends Address = typeof P_VOTE_PROGRAM_ADDRESS,
>(config?: {
  programAddress?: TProgramAddress;
}): RedeemWinningsInstruction<TProgramAddress> {
  // Program address.
  const programAddress = config?.programAddress ?? P_VOTE_PROGRAM_ADDRESS;

  const instruction = {
    programAddress,
    data: getRedeemWinningsInstructionDataEncoder().encode({}),
  } as RedeemWinningsInstruction<TProgramAddress>;

  return instruction;
}

export type ParsedRedeemWinningsInstruction<
  TProgram extends string = typeof P_VOTE_PROGRAM_ADDRESS,
> = {
  programAddress: Address<TProgram>;
  data: RedeemWinningsInstructionData;
};

export function parseRedeemWinningsInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedRedeemWinningsInstruction<TProgram> {
  return {
    programAddress: instruction.programAddress,
    data: getRedeemWinningsInstructionDataDecoder().decode(instruction.data),
  };
}
