//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#initialize_platform;
  pub(crate) mod r#initialize_vote;
  pub(crate) mod r#intitialize_position;
  pub(crate) mod r#redeem_winnings;
  pub(crate) mod r#update_platform;
  pub(crate) mod r#update_position;

  pub use self::r#initialize_platform::*;
  pub use self::r#initialize_vote::*;
  pub use self::r#intitialize_position::*;
  pub use self::r#redeem_winnings::*;
  pub use self::r#update_platform::*;
  pub use self::r#update_position::*;

