/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum PTokenProgramError {
  InvalidDiscriminator,
  PlatformKeyIncorrect,
  VaultKeyIncorrect,
  VoteVaultKeyIncorrect,
  PositionKeyIncorrect,
  VoteVaultTokenAccountIncorrect,
  VoteHasAlreadyEnded,
  VoteIsStillRunning,
  VoteWasTied,
  DidNotVoteForWinningSide,
}

export type PTokenProgramErrorArgs = PTokenProgramError;

export function getPTokenProgramErrorEncoder(): FixedSizeEncoder<PTokenProgramErrorArgs> {
  return getEnumEncoder(PTokenProgramError);
}

export function getPTokenProgramErrorDecoder(): FixedSizeDecoder<PTokenProgramError> {
  return getEnumDecoder(PTokenProgramError);
}

export function getPTokenProgramErrorCodec(): FixedSizeCodec<
  PTokenProgramErrorArgs,
  PTokenProgramError
> {
  return combineCodec(
    getPTokenProgramErrorEncoder(),
    getPTokenProgramErrorDecoder(),
  );
}
