/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from '@solana/kit';

export type UpdatesPositionInstructionData = { amount: ReadonlyUint8Array };

export type UpdatesPositionInstructionDataArgs = UpdatesPositionInstructionData;

export function getUpdatesPositionInstructionDataEncoder(): FixedSizeEncoder<UpdatesPositionInstructionDataArgs> {
  return getStructEncoder([['amount', fixEncoderSize(getBytesEncoder(), 8)]]);
}

export function getUpdatesPositionInstructionDataDecoder(): FixedSizeDecoder<UpdatesPositionInstructionData> {
  return getStructDecoder([['amount', fixDecoderSize(getBytesDecoder(), 8)]]);
}

export function getUpdatesPositionInstructionDataCodec(): FixedSizeCodec<
  UpdatesPositionInstructionDataArgs,
  UpdatesPositionInstructionData
> {
  return combineCodec(
    getUpdatesPositionInstructionDataEncoder(),
    getUpdatesPositionInstructionDataDecoder(),
  );
}
