//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#initialize_platform_instruction_data;
  pub(crate) mod r#initialize_position_instruction_data;
  pub(crate) mod r#initialize_vote_instruction_data;
  pub(crate) mod r#p_token_program_error;
  pub(crate) mod r#redeem_winnings_instruction_data;
  pub(crate) mod r#update_platform_instruction_data;
  pub(crate) mod r#updates_position_instruction_data;

  pub use self::r#initialize_platform_instruction_data::*;
  pub use self::r#initialize_position_instruction_data::*;
  pub use self::r#initialize_vote_instruction_data::*;
  pub use self::r#p_token_program_error::*;
  pub use self::r#redeem_winnings_instruction_data::*;
  pub use self::r#update_platform_instruction_data::*;
  pub use self::r#updates_position_instruction_data::*;

